Global:
  debug: false
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 100
  print_batch_step: 5
  save_model_dir: C:/Users/User/Desktop/Paddle/overall_ocr_system/trained_model_v5/
  save_epoch_step: 100
  eval_batch_step: [0, 20]
  cal_metric_during_train: true
  pretrained_model: C:/Users/User/Desktop/Paddle/overall_ocr_system/trained_model_v4/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: C:/Users/User/Desktop/Paddle/overall_ocr_system/doc/imgs_words/en/1.jpg
  character_dict_path: C:/Users/User/Desktop/Paddle/overall_ocr_system/ppocr/utils/en_dict.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: C:/Users/User/Desktop/Paddle/overall_ocr_system/output/rec/predicts_ic15.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [100,200]
    values: [0.00005,0.00001]
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 0


Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/User/Desktop/Paddle/overall_ocr_system/rec_surya/train
    ext_op_transform_idx: 1
    label_file_list:
    - C:/Users/User/Desktop/Paddle/overall_ocr_system/rec_surya/train_label.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: true
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/User/Desktop/Paddle/overall_ocr_system/rec_surya/test
    label_file_list:
    - C:/Users/User/Desktop/Paddle/overall_ocr_system/rec_surya/test_label.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 64
    num_workers: 4
